package iped.distributed.audit;

import java.time.Instant;

/**
 * Immutable chain-of-custody record for one processing outcome event.
 *
 * <p>Created from an {@link iped.distributed.status.ItemStatusEvent} of type
 * {@code COMPLETED}, {@code ERROR}, or {@code TIMEOUT}.
 *
 * @param itemUuid      UUID of the processed item
 * @param caseId        case this item belongs to
 * @param taskType      task that processed the item ({@code null} for {@code TIMEOUT} events
 *                      generated by the coordinator before a STARTED was seen)
 * @param pipelineStage stage number in which the processing occurred
 * @param agentId       ID of the agent that processed the item; {@code null} when the
 *                      status event did not carry agent identity
 * @param processedAt   timestamp of the status event
 * @param durationMs    wall-clock processing time in milliseconds (0 when unknown)
 * @param outcome       one of {@code "COMPLETED"}, {@code "ERROR"}, {@code "TIMEOUT"}
 * @param errorMessage  error detail for {@code ERROR} / {@code TIMEOUT}; {@code null} for
 *                      {@code COMPLETED}
 */
public record ProcessingRecord(
        String  itemUuid,
        String  caseId,
        String  taskType,
        int     pipelineStage,
        String  agentId,
        Instant processedAt,
        long    durationMs,
        String  outcome,
        String  errorMessage
) {
    /** Build from a status event — returns {@code null} for non-outcome event types. */
    public static ProcessingRecord from(iped.distributed.status.ItemStatusEvent e) {
        if (e.getType() == null) return null;
        String outcome = switch (e.getType()) {
            case COMPLETED -> "COMPLETED";
            case ERROR     -> "ERROR";
            case TIMEOUT   -> "TIMEOUT";
            default        -> null;
        };
        if (outcome == null) return null;
        return new ProcessingRecord(
                e.getItemUuid(),
                e.getCaseId(),
                e.getTaskType(),
                e.getPipelineStage(),
                e.getAgentId(),
                e.getTimestamp() != null ? e.getTimestamp() : Instant.now(),
                e.getDurationMs(),
                outcome,
                e.getErrorMessage());
    }
}
