<#
.SYNOPSIS
    Dry-run iped-engine against a test folder using only the core engine tasks.

.DESCRIPTION
    Locates the built release under target/release/, creates a temporary "dryrun"
    profile that restricts execution to the core engine pipeline (hash, signature,
    type/category classification, entropy, Lucene indexing, CSV export), then invokes
    Bootstrap in headless mode.  The temporary profile is removed when the script exits.

    "Core tasks" means everything that lives in iped-engine itself plus the small
    set of foundational iped-tasks entries that the engine cannot run without —
    explicitly excluding: parsing, carving, thumbnails (image/video/doc), regex,
    graph, transcription, named-entity recognition, PhotoDNA, ElasticSearch, MinIO,
    HTML reports, and all Python/script tasks.

.PARAMETER TestFolder
    Path to the folder to ingest.  Must already exist.

.PARAMETER OutputFolder
    Where IPED writes its output.  Defaults to a timestamped folder under $env:TEMP.
    Deleted on exit unless -KeepOutput is set.

.PARAMETER IpedHome
    Path to the built IPED release directory.
    Defaults to <repo-root>/target/release/iped-<version from pom.xml>.

.PARAMETER KeepOutput
    When set, the output folder is NOT deleted after the run.

.EXAMPLE
    .\dry-run-iped-engine.ps1 -TestFolder C:\evidence\sample

.EXAMPLE
    .\dry-run-iped-engine.ps1 -TestFolder C:\evidence\sample -KeepOutput -OutputFolder C:\tmp\iped-out
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, HelpMessage = 'Folder to ingest (must exist)')]
    [ValidateScript({ Test-Path $_ -PathType Container })]
    [string]$TestFolder,
    [string]$OutputFolder = '',
    [string]$IpedHome = '',
    [switch]$KeepOutput
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Resolve-IpedHome {
    if ($IpedHome) { return $IpedHome }

    $pom = Join-Path $PSScriptRoot 'pom.xml'
    if (-not (Test-Path $pom)) {
        throw "Cannot find pom.xml at $pom. Pass -IpedHome explicitly."
    }
    $version = ([xml](Get-Content $pom -Raw)).project.version
    $candidate = Join-Path $PSScriptRoot "target\release\iped-$version"
    if (-not (Test-Path (Join-Path $candidate 'iped.jar'))) {
        throw @"
Release not found at: $candidate
Build the project first:
    mvn install -DskipTests -q
"@
    }
    return $candidate
}

function Get-JavaMajorVersion {
    param([string]$JavaBin)
    try {
        # "java -version" writes to stderr; redirect so we can capture it
        $raw = & $JavaBin -version 2>&1 | Select-Object -First 1
        if ($raw -match '"(\d+)') { return [int]$Matches[1] }
    } catch { }
    return 0
}

function Resolve-Java {
    param([string]$IpedHome)

    # Candidates in preference order:
    #   1. JAVA_HOME env var (set by the JDK used to build the project)
    #   2. java on PATH
    #   3. Embedded JRE bundled with the release
    $candidates = @()
    if ($env:JAVA_HOME) {
        $candidates += Join-Path $env:JAVA_HOME 'bin\java.exe'
    }
    $candidates += 'java'
    $candidates += (Join-Path $IpedHome 'jre\bin\java.exe')

    foreach ($candidate in $candidates) {
        if ($candidate -ne 'java' -and -not (Test-Path $candidate -ErrorAction SilentlyContinue)) {
            continue
        }
        $major = Get-JavaMajorVersion -JavaBin $candidate
        if ($major -ge 16) {
            Write-Host "      Java $major found: $candidate"
            return $candidate
        }
        if ($major -gt 0) {
            Write-Warning "Skipping $candidate (Java $major < 16 required)."
        }
    }
    throw "No Java >= 16 found. Set JAVA_HOME or add a suitable JDK to PATH."
}

# ---------------------------------------------------------------------------
# Profile content
# ---------------------------------------------------------------------------

# Only the tasks that belong to the engine core pipeline.
# Strips: transcript, image/video/doc thumbs, QR, regex, NER, language detect,
#         previews, PhotoDNA, DIE, remote classifier, Python tasks, MinIO,
#         ElasticSearch, graph, and HTML report.
$taskInstallerXml = @'
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Dry-run task list: only core iped-engine pipeline tasks.
    Generated by dry-run-iped-engine.ps1 — do not edit by hand.
-->
<tasks>
    <task class="iped.engine.task.IgnoreHardLinkTask"></task>
    <task class="iped.engine.task.TempFileTask"></task>
    <task class="iped.engine.task.HashTask"></task>
    <task class="iped.engine.task.SignatureTask"></task>
    <task class="iped.engine.task.SetTypeTask"></task>
    <task class="iped.engine.task.SetCategoryTask"></task>
    <task class="iped.engine.task.DuplicateTask"></task>
    <task class="iped.engine.task.EntropyTask"></task>
    <!-- IndexTask is auto-registered via ServiceLoader (iped-tasks-storage-index) -->
    <task class="iped.engine.task.ExportCSVTask"></task>
</tasks>
'@

# Disable every optional/heavy feature.  Matches the set of flags in IPEDConfig.toml.
$ipedConfigTxt = @'
########################################################################
# Dry-run profile — only core iped-engine tasks are active.
# Generated by dry-run-iped-engine.ps1 — do not edit by hand.
########################################################################

# Core tasks kept ON
enableHash                  = true
processFileSignatures       = true
exportFileProps             = true
entropyTest                 = true

# Everything else OFF
enablePhotoDNA              = false
enableHashDBLookup          = false
enablePhotoDNALookup        = false
enableLedDie                = false
enableYahooNSFWDetection    = false
enableCSAMDetector          = false
ignoreDuplicates            = false
enableFileParsing           = false
expandContainers            = false
processEmbeddedDisks        = false
enableRegexSearch           = false
enableAutomaticExportFiles  = false
enableLanguageDetect        = false
enableNamedEntityRecogniton = false
enableGraphGeneration       = false
indexFileContents           = false
enableIndexToElasticSearch  = false
enableMinIO                 = false
enableOCR                   = false
enableAudioTranscription    = false
enableCarving               = false
enableLedCarving            = false
enableKnownMetCarving       = false
enableImageThumbs           = false
enableImageSimilarity       = false
enableFaceRecognition       = false
enableAgeEstimation         = false
enableSearchHardwareWallets = false
enableVideoThumbs           = false
enableDocThumbs             = false
enableHTMLReport            = false
enableRemoteImageClassifier = false
enableQRCode                = false
'@

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

$ipedHome    = Resolve-IpedHome
$java        = Resolve-Java -IpedHome $ipedHome
$ipedJar     = Join-Path $ipedHome 'iped.jar'
$profileName = 'dryrun'
$profileDir  = Join-Path $ipedHome "profiles\$profileName"
$profileConf = Join-Path $profileDir 'conf'

if (-not $OutputFolder) {
    $timestamp    = Get-Date -Format 'yyyyMMdd-HHmmss'
    $OutputFolder = Join-Path $env:TEMP "iped-dryrun-$timestamp"
}

# Normalise paths
$TestFolder   = (Resolve-Path $TestFolder).Path
$OutputFolder = [System.IO.Path]::GetFullPath($OutputFolder)

Write-Host ''
Write-Host '=== iped-engine dry run ==='
Write-Host "  IPED home   : $ipedHome"
Write-Host "  Java        : $java"
Write-Host "  Test folder : $TestFolder"
Write-Host "  Output      : $OutputFolder"
Write-Host "  Profile     : $profileName"
Write-Host ''

# ---------------------------------------------------------------------------
# Create temporary dryrun profile
# ---------------------------------------------------------------------------

try {
    Write-Host '[1/3] Creating dryrun profile...'
    New-Item -ItemType Directory -Force -Path $profileConf | Out-Null

    $ipedConfigTxt    | Set-Content -Path (Join-Path $profileDir 'IPEDConfig.toml')  -Encoding UTF8
    $taskInstallerXml | Set-Content -Path (Join-Path $profileConf 'TaskInstaller.xml') -Encoding UTF8

    Write-Host "      Profile written to $profileDir"

    # ---------------------------------------------------------------------------
    # Invoke IPED Bootstrap
    # ---------------------------------------------------------------------------

    Write-Host '[2/3] Running iped-engine...'
    Write-Host ''

    $args = @(
        '-jar', $ipedJar,
        '-d',  $TestFolder,
        '-o',  $OutputFolder,
        '-profile', $profileName,
        '--nogui',
        '--nologfile'
    )

    $proc = Start-Process -FilePath $java `
                          -ArgumentList $args `
                          -NoNewWindow `
                          -PassThru `
                          -Wait

    Write-Host ''
    if ($proc.ExitCode -eq 0) {
        Write-Host '[3/3] IPED finished successfully.' -ForegroundColor Green
    } else {
        Write-Warning "[3/3] IPED exited with code $($proc.ExitCode)."
    }

} finally {
    # Always remove the temporary profile so it does not pollute the release tree.
    if (Test-Path $profileDir) {
        Remove-Item -Recurse -Force $profileDir
        Write-Host "      Temporary profile removed."
    }
}

# ---------------------------------------------------------------------------
# Report output location / cleanup
# ---------------------------------------------------------------------------

if ($KeepOutput) {
    Write-Host ''
    Write-Host "Output kept at: $OutputFolder"
} else {
    if (Test-Path $OutputFolder) {
        Remove-Item -Recurse -Force $OutputFolder
        Write-Host "Output folder removed (use -KeepOutput to keep it)."
    }
}

Write-Host ''
