package iped.distributed.agent;

import iped.data.ICaseData;
import iped.data.IItem;
import iped.distributed.config.DistributedConfig;
import iped.distributed.coordinator.AgentRegistration;
import iped.distributed.coordinator.CoordinatorClient;
import iped.distributed.kafka.*;
import iped.distributed.resource.PressureLevel;
import iped.distributed.resource.ResourcePressure;
import iped.distributed.resource.ResourcePressureMonitor;
import iped.distributed.resource.ResourcePressurePolicy;
import iped.distributed.security.KafkaSecurityConfigurer;
import iped.distributed.security.PayloadSigner;
import iped.distributed.status.ItemStatusProducer;
import iped.engine.datasource.DatasourceRegistry;
import iped.engine.datasource.IDatasourceRegistry;
import java.time.Duration;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.Semaphore;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import lombok.extern.slf4j.Slf4j;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.consumer.OffsetAndMetadata;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.TopicPartition;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;

/**
 * Distributed Task Agent — the execution unit of the IPED distributed pipeline.
 *
 * <p>A Task Agent:
 *
 * <ol>
 *   <li>Subscribes to its input Kafka topic (stage N) using a consumer group named {@code
 *       {caseId}.{taskType}}, ensuring exactly <em>one</em> agent of each type processes each item.
 *   <li>Deserialises {@link KafkaItemMessage} → {@link IItem}.
 *   <li>Executes the configured {@link Runnable} task processor (a thin wrapper around the
 *       unchanged {@code AbstractTask}).
 *   <li>Serialises the updated item state back to a {@link KafkaItemMessage} and publishes it to
 *       the output topic (stage N+1).
 *   <li>Publishes status events to the global {@code iped.status} topic.
 *   <li>Re-injects sub-items generated by the task into stage-0 topic.
 * </ol>
 *
 * <p><b>Thread model</b>: one Kafka consumer thread polls the input topic. Items are handed off to
 * a {@link ThreadPoolExecutor} of size {@code parallelism}. When all slots are full the consumer
 * pauses partition consumption (backpressure).
 *
 * <p>Task code is completely unchanged — it never imports anything from this class.
 *
 * <h2>Graceful drain vs hard stop</h2>
 *
 * <p>Two shutdown modes are available:
 *
 * <ul>
 *   <li><b>{@link #drain()}</b> — graceful, for coordinated rolling restarts (SIGTERM). Pauses all
 *       Kafka partitions (no new records accepted), waits for in-flight items to finish, calls
 *       {@code producer.flush()} so every async send callback ({@code tracker.markDone}) fires,
 *       then commits and exits. Items that were in-flight complete normally and are not
 *       re-delivered to the next instance.
 *   <li><b>{@link #stop()}</b> — immediate, for unrecoverable errors. Sets {@code running = false};
 *       the shutdown path still flushes the producer and commits any watermark that advanced, but
 *       in-flight items that have not yet reached their send callback will be re-delivered on
 *       restart (at-least-once semantics).
 * </ul>
 *
 * <p><b>Signal handling</b>: callers should register a JVM shutdown hook that calls {@code
 * agent.drain()} on SIGTERM/SIGINT and awaits {@code start()} returning.
 *
 * <h2>Idempotency contract</h2>
 *
 * <p>The agent provides <em>at-least-once</em> delivery: an item may be re-processed after an agent
 * restart if its Kafka offset was not yet committed when the JVM exited. All components in the
 * pipeline are designed to be idempotent under re-delivery:
 *
 * <ul>
 *   <li><b>Parent items</b>: the {@code itemUuid} is stable (carried in the message). Downstream
 *       Lucene indexing uses {@code updateDocument(itemUuid, …)}, so a re-processed item overwrites
 *       its earlier entry without creating a duplicate.
 *   <li><b>Sub-items</b>: UUIDs are derived deterministically from {@code (parentItemUuid,
 *       ordinal)} via {@link ItemConverter#deterministicSubitemUuid}. Tasks must emit sub-items in
 *       a stable order for the same input (all built-in IPED tasks satisfy this by iterating
 *       container entries in index/offset order). Re-delivering the parent therefore yields
 *       sub-items with the same UUIDs, and the downstream upsert overwrites rather than duplicates
 *       them.
 *   <li><b>Retry messages</b> (items re-published to the input topic after failure): the {@code
 *       attempt} counter increments on each retry, so the agent can distinguish a retry from a
 *       fresh delivery; task code sees a normal {@link IItem} in both cases.
 * </ul>
 *
 * <p>Tasks that create external side-effects beyond the Kafka pipeline (e.g. writing files to the
 * shared output directory) must ensure those writes are overwrite-safe (same path for the same item
 * UUID on every run).
 */
@Slf4j
public class TaskAgent implements AutoCloseable {

  // ---- Configuration -----------------------------------------------------

  private final String agentId;
  private final String caseId; // null in multi-case mode
  private final String taskType; // e.g. "HashTask"
  private final int stageNumber; // input stage (same for all cases for this task type)
  private final String inputTopic; // null in multi-case mode
  private final String outputTopic; // null in multi-case mode
  private final String rawTopic; // null in multi-case mode

  // ---- Multi-case steering -----------------------------------------------
  /** True when this agent was created without a fixed case; subscription driven by coordinator. */
  private final boolean multiCaseMode;

  /** Topics pending subscription update from the latest heartbeat response (null = no change). */
  private volatile List<String> pendingTopicUpdate = null;

  /** Topics currently subscribed to; compared with heartbeat response to detect changes. */
  private volatile List<String> currentSubscription = Collections.emptyList();

  // ---- Kafka -------------------------------------------------------------

  private final KafkaConsumer<String, KafkaItemMessage> consumer;
  private final KafkaProducer<String, KafkaItemMessage> producer;
  private final ItemStatusProducer statusProducer;

  // ---- Task execution ----------------------------------------------------

  /**
   * Functional interface that wraps a single task execution. The implementation calls {@code
   * task.process(item)} and returns. Tasks are instantiated outside this class (e.g. in {@link
   * TaskAgentLauncher}).
   */
  @FunctionalInterface
  public interface TaskProcessor {
    void process(IItem item) throws Exception;
  }

  private final TaskProcessor taskProcessor;
  private final int parallelism;
  private final ThreadPoolExecutor executor;
  private final Semaphore slots; // bounds in-flight items

  // ---- State -------------------------------------------------------------

  private final AtomicInteger inFlight = new AtomicInteger(0);
  private volatile boolean running = true;
  private volatile boolean draining = false;
  private volatile ResourcePressure lastPressure = ResourcePressure.none();
  private final CoordinatorClient coordinator;
  private final DistributedConfig cfg;
  private final ResourcePressureMonitor pressureMonitor;
  private final PartitionOffsetTracker tracker = new PartitionOffsetTracker();

  // -----------------------------------------------------------------------
  // Constructor
  // -----------------------------------------------------------------------

  /**
   * Single-case constructor (backward-compatible). The agent subscribes to one fixed case topic and
   * uses {@code caseId.taskType} as the consumer group.
   */
  public TaskAgent(
      String caseId,
      String taskType,
      int stageNumber,
      TaskProcessor taskProcessor,
      DistributedConfig cfg,
      CoordinatorClient coordinator) {
    this.agentId = UUID.randomUUID().toString();
    this.caseId = caseId;
    this.taskType = taskType;
    this.stageNumber = stageNumber;
    this.inputTopic = TopicProvisioner.stageTopic(caseId, stageNumber);
    this.outputTopic = TopicProvisioner.stageTopic(caseId, stageNumber + 1);
    this.rawTopic = TopicProvisioner.stageTopic(caseId, 0);
    this.multiCaseMode = false;
    this.taskProcessor = taskProcessor;
    this.parallelism = cfg.getAgentParallelism();
    this.cfg = cfg;
    this.coordinator = coordinator;

    this.slots = new Semaphore(parallelism);
    this.executor =
        new ThreadPoolExecutor(
            parallelism,
            parallelism,
            60L,
            TimeUnit.SECONDS,
            new LinkedBlockingQueue<>(parallelism * 2),
            r -> {
              Thread t = new Thread(r, taskType + "-worker-" + agentId.substring(0, 8));
              return t;
            },
            new ThreadPoolExecutor.CallerRunsPolicy());

    this.consumer = buildConsumer(cfg);
    this.producer = buildProducer(cfg);
    this.statusProducer = new ItemStatusProducer(cfg.getKafkaBootstrapServers(), this.agentId);

    ResourcePressurePolicy policy = ResourcePressurePolicy.fromConfig(cfg);
    this.pressureMonitor =
        ResourcePressureMonitor.forAgent(
            policy, java.nio.file.Path.of(cfg.getSharedStorageRoot()), null);

    log.info(
        "TaskAgent created (single-case): taskType={}, stage={}, input={}, output={}, parallelism={}",
        taskType,
        stageNumber,
        inputTopic,
        outputTopic,
        parallelism);
  }

  /**
   * Multi-case constructor. The agent is task-type-scoped (not bound to one case); it subscribes to
   * the topics returned by the coordinator heartbeat response and uses {@code taskType} as the
   * consumer group so all agents of the same type share offset tracking across all case topics.
   *
   * <p>The initial subscription is empty — the first heartbeat response populates it.
   */
  public TaskAgent(
      String taskType,
      int stageNumber,
      TaskProcessor taskProcessor,
      DistributedConfig cfg,
      CoordinatorClient coordinator) {
    this.agentId = UUID.randomUUID().toString();
    this.caseId = null;
    this.taskType = taskType;
    this.stageNumber = stageNumber;
    this.inputTopic = null;
    this.outputTopic = null;
    this.rawTopic = null;
    this.multiCaseMode = true;
    this.taskProcessor = taskProcessor;
    this.parallelism = cfg.getAgentParallelism();
    this.cfg = cfg;
    this.coordinator = coordinator;

    this.slots = new Semaphore(parallelism);
    this.executor =
        new ThreadPoolExecutor(
            parallelism,
            parallelism,
            60L,
            TimeUnit.SECONDS,
            new LinkedBlockingQueue<>(parallelism * 2),
            r -> {
              Thread t = new Thread(r, taskType + "-worker-" + agentId.substring(0, 8));
              return t;
            },
            new ThreadPoolExecutor.CallerRunsPolicy());

    this.consumer = buildConsumer(cfg);
    this.producer = buildProducer(cfg);
    this.statusProducer = new ItemStatusProducer(cfg.getKafkaBootstrapServers(), this.agentId);

    ResourcePressurePolicy policy = ResourcePressurePolicy.fromConfig(cfg);
    this.pressureMonitor =
        ResourcePressureMonitor.forAgent(
            policy, java.nio.file.Path.of(cfg.getSharedStorageRoot()), null);

    log.info(
        "TaskAgent created (multi-case): taskType={}, stage={}, parallelism={}",
        taskType,
        stageNumber,
        parallelism);
  }

  // -----------------------------------------------------------------------
  // Lifecycle
  // -----------------------------------------------------------------------

  /**
   * Starts the agent — blocks until {@link #stop()} or {@link #drain()} causes the consumer loop to
   * exit.
   */
  public void start() {
    coordinator.register(
        AgentRegistration.of(
            agentId,
            taskType,
            stageNumber,
            parallelism,
            java.net.InetAddress.getLoopbackAddress().getHostName()));

    if (!multiCaseMode) {
      consumer.subscribe(Collections.singletonList(inputTopic));
      currentSubscription = Collections.singletonList(inputTopic);
      log.info("TaskAgent '{}' (type={}) subscribed to '{}'", agentId, taskType, inputTopic);
    } else {
      log.info(
          "TaskAgent '{}' (type={}) multi-case mode — awaiting topic assignment from coordinator",
          agentId,
          taskType);
    }

    Thread heartbeatThread = new Thread(this::heartbeatLoop, taskType + "-heartbeat");
    heartbeatThread.setDaemon(true);
    heartbeatThread.start();

    try {
      while (running) {
        // ── Graceful drain ────────────────────────────────────────────
        // Pause all assigned partitions so poll() returns empty batches.
        // Once the executor is idle, flush the producer so every async
        // send callback (markDone) fires before we commit and exit.
        if (draining) {
          Set<TopicPartition> assignment = consumer.assignment();
          if (!assignment.isEmpty()) {
            consumer.pause(assignment);
          }
          if (inFlight.get() == 0) {
            log.info(
                "TaskAgent '{}' drain complete ({} in-flight) — flushing producer", agentId, 0);
            flushProducer();
            break; // fall through to finally for final commit and close
          }
        }
        // ─────────────────────────────────────────────────────────────

        // ── Resource backpressure intake pause ────────────────────────
        // When HARD, pause all partitions so poll() returns empty batches;
        // resume automatically when pressure drops.  In-flight items always
        // finish — only NEW work is withheld.  Skipped entirely during drain
        // because draining already pauses the same partitions.
        if (!draining) {
          Set<TopicPartition> assignment = consumer.assignment();
          if (lastPressure.level() == PressureLevel.HARD) {
            if (!assignment.isEmpty()) consumer.pause(assignment);
          } else {
            Set<TopicPartition> paused = consumer.paused();
            if (!paused.isEmpty()) {
              consumer.resume(paused);
              log.info(
                  "TaskAgent '{}' resource pressure cleared to {} — intake resumed",
                  agentId,
                  lastPressure.level());
            }
          }
        }
        // ─────────────────────────────────────────────────────────────

        // ── Multi-case dynamic subscription update ────────────────────
        // The heartbeat loop signals topic changes via pendingTopicUpdate.
        // consumer.subscribe() must be called from the consumer thread (here).
        List<String> pending = pendingTopicUpdate;
        if (pending != null) {
          pendingTopicUpdate = null;
          if (!pending.equals(currentSubscription)) {
            if (pending.isEmpty()) {
              consumer.unsubscribe();
              log.info(
                  "TaskAgent '{}' unsubscribed — no active cases for type={}", agentId, taskType);
            } else {
              consumer.subscribe(pending);
              log.info(
                  "TaskAgent '{}' subscription updated: {} → {}",
                  agentId,
                  currentSubscription,
                  pending);
            }
            currentSubscription = pending;
          }
        }
        // ─────────────────────────────────────────────────────────────

        ConsumerRecords<String, KafkaItemMessage> records = consumer.poll(Duration.ofMillis(500));

        for (ConsumerRecord<String, KafkaItemMessage> record : records) {
          // Do not accept new work during drain or after stop()
          if (!running || draining) break;
          TopicPartition tp = new TopicPartition(record.topic(), record.partition());
          // Register the offset BEFORE submitting so markDone can never race ahead
          tracker.recordPolled(tp, record.offset());
          // Acquire a processing slot (backpressure)
          try {
            slots.acquire();
          } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            break;
          }
          inFlight.incrementAndGet();
          final KafkaItemMessage msg = record.value();
          final long recordOffset = record.offset();
          executor.submit(() -> processRecord(msg, tp, recordOffset));
        }

        // Commit whatever watermarks have advanced since the last poll
        Map<TopicPartition, OffsetAndMetadata> committable = tracker.drainCommittable();
        if (!committable.isEmpty()) {
          consumer.commitAsync(
              committable,
              (offsets, ex) -> {
                if (ex != null) {
                  log.warn("Async offset commit failed for {}: {}", offsets, ex.getMessage());
                } else {
                  log.debug("Committed offsets: {}", offsets);
                }
              });
        }
      }
    } finally {
      log.info("TaskAgent '{}' consumer loop exiting (draining={})", agentId, draining);
      executor.shutdown();
      try {
        executor.awaitTermination(60, TimeUnit.SECONDS);
      } catch (InterruptedException ignored) {
      }
      // Flush pending producer sends so that every markDone callback fires BEFORE we
      // call drainCommittable() and commitSync().  Without this flush, items whose
      // producer.send callback has not yet fired would miss the final offset commit
      // and be re-delivered unnecessarily (producer.close() flushes too late — it
      // runs after commitSync, so those markDone calls arrive after the commit).
      flushProducer();
      Map<TopicPartition, OffsetAndMetadata> remaining = tracker.drainCommittable();
      if (!remaining.isEmpty()) {
        try {
          consumer.commitSync(remaining);
          log.info("TaskAgent '{}' committed final offsets on shutdown: {}", agentId, remaining);
        } catch (Exception ex) {
          log.warn("TaskAgent '{}' failed to commit final offsets on shutdown", agentId, ex);
        }
      }
      consumer.close();
      producer.close();
      statusProducer.close();
      coordinator.unregister(agentId);
    }
  }

  /**
   * Requests an immediate shutdown. The consumer loop exits on the next iteration; in-flight items
   * may not complete and will be re-delivered on the next agent start. Prefer {@link #drain()} for
   * coordinated rolling restarts.
   */
  public void stop() {
    running = false;
  }

  /**
   * Initiates a graceful drain for coordinated rolling restarts (SIGTERM / SIGINT).
   *
   * <p>Sets the {@code draining} flag. The consumer loop then:
   *
   * <ol>
   *   <li>Pauses all assigned Kafka partitions — no new records are polled.
   *   <li>Waits (by spinning the poll loop on empty batches) until all in-flight items complete.
   *   <li>Calls {@code producer.flush()} to ensure every async send callback ({@code
   *       tracker.markDone}) has fired.
   *   <li>Exits the loop; the {@code finally} block commits remaining offsets and closes all
   *       resources.
   * </ol>
   *
   * <p>Items that were in-flight when {@code drain()} was called complete normally and are
   * committed — they will <em>not</em> be re-delivered to the next agent instance, unlike a hard
   * {@link #stop()}.
   *
   * <p>Typical usage from a JVM shutdown hook:
   *
   * <pre>{@code
   * Runtime.getRuntime().addShutdownHook(new Thread(() -> {
   *     agent.drain();
   *     // start() will return once the drain completes
   * }));
   * }</pre>
   */
  public void drain() {
    log.info(
        "TaskAgent '{}' drain requested — pausing intake, waiting for {} in-flight item(s)",
        agentId,
        inFlight.get());
    draining = true;
  }

  private void flushProducer() {
    try {
      producer.flush();
    } catch (Exception ex) {
      log.warn(
          "TaskAgent '{}' producer flush failed during shutdown: {}", agentId, ex.getMessage());
    }
  }

  // -----------------------------------------------------------------------
  // Item processing
  // -----------------------------------------------------------------------

  private void processRecord(KafkaItemMessage msg, TopicPartition partition, long offset) {
    long startMs = System.currentTimeMillis();
    try {
      // Poison-message guard — deserializer returns a sentinel when raw bytes cannot
      // be parsed (see KafkaItemDeserializer).  Skip task execution and route directly
      // to the DLQ so the partition continues; do NOT retry (attempt stays 0).
      if (KafkaItemDeserializer.isPoison(msg)) {
        String errMsg =
            String.valueOf(msg.getExtraAttributes().get(KafkaItemDeserializer.POISON_ERROR_KEY));
        log.error(
            "Poison message at {}@{}: {} — routing to DLQ without task execution",
            partition,
            offset,
            errMsg);
        statusProducer.publishError(
            msg, taskType, 0, new RuntimeException("Poison message: " + errMsg));
        sendToDeadLetterQueue(
            msg, new RuntimeException("Poison message: " + errMsg), partition, offset);
        return;
      }

      // Payload signature verification (chain-of-custody integrity check)
      String sigSecret = cfg.getPayloadSigningSecret();
      if (PayloadSigner.isEnabled(sigSecret)) {
        if (!PayloadSigner.verify(msg, sigSecret)) {
          log.error(
              "Payload signature verification FAILED for item '{}' at {}@{} — routing to DLQ",
              msg.getItemUuid(),
              partition,
              offset);
          statusProducer.publishError(
              msg, taskType, 0, new SecurityException("Payload signature verification failed"));
          sendToDeadLetterQueue(
              msg,
              new SecurityException("Payload signature verification failed"),
              partition,
              offset);
          return;
        }
      }

      // Honour the retry backoff window set by handleFailure()
      long waitMs = msg.getNotBeforeMs() - System.currentTimeMillis();
      if (waitMs > 0) {
        log.debug(
            "Item '{}' attempt {} delayed {}ms (backoff)",
            msg.getItemUuid(),
            msg.getAttempt(),
            waitMs);
        Thread.sleep(waitMs);
        startMs = System.currentTimeMillis();
      }
      log.debug("Processing item '{}' ({})", msg.getItemUuid(), msg.getPath());
      statusProducer.publishStarted(msg, taskType);

      // Deserialise to IItem
      IItem item = ItemConverter.toItem(msg);
      item.setTempAttribute(ItemConverter.ATTR_KAFKA_MSG, msg);

      // Override DatasourceRegistry for THIS thread so that any sub-items
      // generated by the task go back to stage.0 (full pipeline re-entry).
      IDatasourceRegistry prevRegistry = DatasourceRegistry.get();
      DatasourceRegistry.set(buildSubitemRegistry(msg));
      try {
        // *** Task code runs here — completely unchanged ***
        taskProcessor.process(item);
      } finally {
        DatasourceRegistry.set(prevRegistry);
      }

      // Forward updated item to next stage; retry counters are per-stage.
      // markDone is called in the producer callback so the consumer offset is
      // committed only after the broker durably acknowledges the forwarded record.
      // Derive the output topic from the message's caseId — correct for both
      // single-case (where msg.getCaseId() == this.caseId) and multi-case mode.
      final String effectiveOutputTopic =
          TopicProvisioner.stageTopic(msg.getCaseId(), stageNumber + 1);
      KafkaItemMessage updated = ItemConverter.mergeState(msg, item);
      updated.setAttempt(0);
      updated.setNotBeforeMs(0);
      if (PayloadSigner.isEnabled(cfg.getPayloadSigningSecret())) {
        PayloadSigner.sign(updated, cfg.getPayloadSigningSecret());
      }
      final long durationMs = System.currentTimeMillis() - startMs;
      producer.send(
          new ProducerRecord<>(effectiveOutputTopic, updated.getItemUuid(), updated),
          (meta, ex) -> {
            if (ex != null) {
              log.error(
                  "Failed to forward item '{}' to '{}', parking in DLQ",
                  msg.getItemUuid(),
                  effectiveOutputTopic,
                  ex);
              // Forward failed — park in DLQ and still mark done so the
              // consumer can advance; losing the item silently would be worse.
              sendToDeadLetterQueue(msg, ex, partition, offset);
            } else {
              tracker.markDone(partition, offset);
              statusProducer.publishCompleted(msg, taskType, durationMs);
              log.debug("Completed item '{}' in {}ms", msg.getItemUuid(), durationMs);
            }
          });

    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      // Do NOT mark done — the item will be re-delivered on restart, which is correct.
      log.warn("Interrupted while processing item '{}'; offset not committed", msg.getItemUuid());
    } catch (Exception e) {
      handleFailure(msg, e, System.currentTimeMillis() - startMs, partition, offset);
    } finally {
      inFlight.decrementAndGet();
      slots.release();
    }
  }

  /**
   * Returns a {@link IDatasourceRegistry} that redirects sub-item creation back to stage-0 (raw
   * topic) so sub-items flow through the full pipeline.
   *
   * <p><b>Idempotency contract:</b> each sub-item is assigned a UUID derived deterministically from
   * its parent's UUID and its ordinal position in the emission sequence (0, 1, 2 …). Tasks are
   * expected to emit sub-items in a stable order for the same input, which is true for all built-in
   * IPED tasks (they iterate container entries in index/offset order). As a result, re-delivering
   * the parent item after an agent restart causes the task to emit the same sub-items with the same
   * UUIDs, and downstream stages overwrite rather than duplicate them.
   */
  private IDatasourceRegistry buildSubitemRegistry(KafkaItemMessage parentMsg) {
    IDatasourceRegistry base = DatasourceRegistry.get();
    AtomicInteger subitemOrdinal = new AtomicInteger(0);
    return new IDatasourceRegistry() {
      @Override
      public IItem createItem() {
        return base.createItem();
      }

      @Override
      public void addItem(IItem subItem) {
        // Assign deterministic UUID before toMessage() so it is not randomised
        String subUuid =
            ItemConverter.deterministicSubitemUuid(
                parentMsg.getItemUuid(), subitemOrdinal.getAndIncrement());
        subItem.setTempAttribute(ItemConverter.ATTR_ITEM_UUID, subUuid);
        // Use parentMsg.getCaseId() so sub-items land in the right case's stage-0,
        // correct for both single-case (== this.caseId) and multi-case mode.
        String msgCaseId = parentMsg.getCaseId();
        KafkaItemMessage subMsg = ItemConverter.toMessage(subItem, msgCaseId);
        subMsg.setParentItemUuid(parentMsg.getItemUuid());
        String subRawTopic = TopicProvisioner.stageTopic(msgCaseId, 0);
        producer.send(new ProducerRecord<>(subRawTopic, subMsg.getItemUuid(), subMsg));
        statusProducer.publishSubitemDiscovered(subMsg);
      }

      @Override
      public void addItemFirst(IItem subItem) {
        addItem(subItem);
      }

      @Override
      public void prepareForQueue(IItem item, ICaseData caseData) {
        base.prepareForQueue(item, caseData);
      }

      @Override
      public String getTrackID(IItem item) {
        return base.getTrackID(item);
      }

      @Override
      public void onProgress(String p, Object o, Object n) {
        base.onProgress(p, o, n);
      }

      @Override
      public void setEnvVar(String k, String v) {
        base.setEnvVar(k, v);
      }
    };
  }

  /**
   * Retry policy: re-publish to the input topic with exponential backoff ({@code base * 2^attempt}
   * seconds) until {@code maxRetries} is exhausted, then park the item in the stage's dead-letter
   * queue.
   *
   * <p>The consumer offset for this record is marked done only once the re-publish or DLQ send is
   * durably acknowledged, preserving at-least-once semantics.
   */
  private void handleFailure(
      KafkaItemMessage msg, Exception e, long durationMs, TopicPartition partition, long offset) {
    statusProducer.publishError(msg, taskType, durationMs, e);

    // Use partition.topic() as the effective input topic — correct for both
    // single-case (== this.inputTopic) and multi-case (the actual subscribed topic).
    String effectiveInputTopic = partition.topic();
    int attempt = msg.getAttempt();
    if (attempt < cfg.getMaxRetries()) {
      long backoffMs = cfg.getRetryBackoffBaseSeconds() * 1000L * (1L << attempt);
      msg.setAttempt(attempt + 1);
      msg.setNotBeforeMs(System.currentTimeMillis() + backoffMs);
      log.warn(
          "Item '{}' failed in '{}' (attempt {}/{}), retrying in {}s: {}",
          msg.getItemUuid(),
          taskType,
          attempt + 1,
          cfg.getMaxRetries(),
          backoffMs / 1000,
          e.getMessage());
      producer.send(
          new ProducerRecord<>(effectiveInputTopic, msg.getItemUuid(), msg),
          (meta, ex) -> {
            if (ex != null) {
              log.error(
                  "Could not re-publish item '{}' for retry, sending to DLQ",
                  msg.getItemUuid(),
                  ex);
              sendToDeadLetterQueue(msg, e, partition, offset);
            } else {
              // Retry message durably queued — safe to advance the watermark.
              tracker.markDone(partition, offset);
            }
          });
    } else {
      log.error(
          "Item '{}' exhausted {} retries in task '{}': {}",
          msg.getItemUuid(),
          cfg.getMaxRetries(),
          taskType,
          e.getMessage(),
          e);
      sendToDeadLetterQueue(msg, e, partition, offset);
    }
  }

  private void sendToDeadLetterQueue(
      KafkaItemMessage msg, Exception cause, TopicPartition partition, long offset) {
    // Use partition.topic() as the effective input topic — correct for both
    // single-case (== this.inputTopic) and multi-case (the actual subscribed topic).
    String dlqTopic = partition.topic() + cfg.getDeadLetterTopicSuffix();
    producer.send(
        new ProducerRecord<>(dlqTopic, msg.getItemUuid(), msg),
        (meta, ex) -> {
          if (ex != null) {
            log.error(
                "Could not send item '{}' to DLQ '{}'; offset will not be committed",
                msg.getItemUuid(),
                dlqTopic,
                ex);
            // Leave offset uncommitted — re-delivery on restart is better than loss.
          } else {
            log.info("Item '{}' sent to DLQ '{}'", msg.getItemUuid(), dlqTopic);
            tracker.markDone(partition, offset);
          }
        });
  }

  // -----------------------------------------------------------------------
  // Heartbeat
  // -----------------------------------------------------------------------

  private void heartbeatLoop() {
    PressureLevel prevLevel = PressureLevel.NONE;
    while (running) {
      try {
        ResourcePressure pressure = pressureMonitor.sample();
        lastPressure = pressure;
        // Log transitions
        if (pressure.level() != prevLevel) {
          if (pressure.level() == PressureLevel.HARD) {
            log.warn(
                "TaskAgent '{}' entering HARD backpressure — pausing intake: {}",
                agentId,
                pressure.reason());
          } else if (prevLevel == PressureLevel.HARD) {
            log.info(
                "TaskAgent '{}' backpressure eased to {} — intake will resume",
                agentId,
                pressure.level());
          } else if (pressure.level() == PressureLevel.SOFT) {
            log.debug("TaskAgent '{}' SOFT backpressure: {}", agentId, pressure.reason());
          }
          prevLevel = pressure.level();
        }
        iped.distributed.coordinator.HeartbeatResponse hbResp =
            coordinator.heartbeat(
                agentId,
                parallelism - inFlight.get(),
                inFlight.get(),
                pressure.level(),
                pressure.heapRatio());
        // In multi-case mode, apply topic changes returned by the coordinator.
        // Signal the poll thread (which owns the consumer) via a volatile field.
        if (multiCaseMode && hbResp != null) {
          List<String> newTopics = hbResp.getSubscribedTopics();
          if (!newTopics.equals(currentSubscription)) {
            pendingTopicUpdate = newTopics;
          }
        }
        Thread.sleep(cfg.getHeartbeatIntervalSeconds() * 1000L);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        break;
      } catch (Exception e) {
        log.warn("Heartbeat failed: {}", e.getMessage());
      }
    }
  }

  // -----------------------------------------------------------------------
  // Kafka builders
  // -----------------------------------------------------------------------

  private KafkaConsumer<String, KafkaItemMessage> buildConsumer(DistributedConfig cfg) {
    Properties props = new Properties();
    props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, cfg.getKafkaBootstrapServers());
    KafkaSecurityConfigurer.apply(props, cfg);
    // Consumer group: single-case uses caseId.taskType (backward-compatible);
    // multi-case uses taskType so all agents of the same type share offset tracking
    // across all subscribed case topics.
    String groupId = multiCaseMode ? taskType : (caseId + "." + taskType);
    props.put(ConsumerConfig.GROUP_ID_CONFIG, groupId);
    props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
    props.put(
        ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, KafkaItemDeserializer.class.getName());
    props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
    // Manual commit via PartitionOffsetTracker — auto-commit would commit offsets
    // before worker threads finish, silently losing items on agent restart.
    props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
    props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, parallelism * 2);
    props.put(
        ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, (int) (cfg.getItemTimeoutSeconds() * 1000L));
    return new KafkaConsumer<>(props);
  }

  private KafkaProducer<String, KafkaItemMessage> buildProducer(DistributedConfig cfg) {
    Properties props = new Properties();
    props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, cfg.getKafkaBootstrapServers());
    KafkaSecurityConfigurer.apply(props, cfg);
    props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, KafkaItemSerializer.class.getName());
    props.put(ProducerConfig.ACKS_CONFIG, "all");
    props.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, true);
    props.put(ProducerConfig.COMPRESSION_TYPE_CONFIG, "lz4");
    props.put(ProducerConfig.LINGER_MS_CONFIG, 5);
    return new KafkaProducer<>(props);
  }

  @Override
  public void close() {
    stop();
  }

  // ---- Accessors ---------------------------------------------------------
  public String getAgentId() {
    return agentId;
  }

  public String getTaskType() {
    return taskType;
  }

  public int getInFlight() {
    return inFlight.get();
  }

  public int getFreeSlots() {
    return slots.availablePermits();
  }
}
