package iped.distributed.agent;

import iped.data.ICaseData;
import iped.data.IItem;
import iped.distributed.config.DistributedConfig;
import iped.distributed.coordinator.AgentRegistration;
import iped.distributed.coordinator.CoordinatorClient;
import iped.distributed.kafka.*;
import iped.distributed.status.ItemStatusProducer;
import iped.engine.datasource.DatasourceRegistry;
import iped.engine.datasource.IDatasourceRegistry;
import org.apache.kafka.clients.consumer.*;
import org.apache.kafka.clients.producer.*;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Duration;
import java.util.Collections;
import java.util.List;
import java.util.Properties;
import java.util.UUID;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Distributed Task Agent — the execution unit of the IPED distributed pipeline.
 *
 * <p>A Task Agent:
 * <ol>
 *   <li>Subscribes to its input Kafka topic (stage N) using a consumer group
 *       named {@code {caseId}.{taskType}}, ensuring exactly <em>one</em> agent of
 *       each type processes each item.</li>
 *   <li>Deserialises {@link KafkaItemMessage} → {@link IItem}.</li>
 *   <li>Executes the configured {@link Runnable} task processor
 *       (a thin wrapper around the unchanged {@code AbstractTask}).</li>
 *   <li>Serialises the updated item state back to a {@link KafkaItemMessage} and
 *       publishes it to the output topic (stage N+1).</li>
 *   <li>Publishes status events to the global {@code iped.status} topic.</li>
 *   <li>Re-injects sub-items generated by the task into stage-0 topic.</li>
 * </ol>
 *
 * <p><b>Thread model</b>: one Kafka consumer thread polls the input topic. Items are
 * handed off to a {@link ThreadPoolExecutor} of size {@code parallelism}. When all
 * slots are full the consumer pauses partition consumption (backpressure).
 *
 * <p>Task code is completely unchanged — it never imports anything from this class.
 */
public class TaskAgent implements AutoCloseable {

    private static final Logger LOGGER = LoggerFactory.getLogger(TaskAgent.class);

    // ---- Configuration -----------------------------------------------------

    private final String           agentId;
    private final String           caseId;
    private final String           taskType;        // e.g. "HashTask"
    private final int              stageNumber;     // input stage
    private final String           inputTopic;
    private final String           outputTopic;
    private final String           rawTopic;        // stage.0 — for sub-item injection

    // ---- Kafka -------------------------------------------------------------

    private final KafkaConsumer<String, KafkaItemMessage> consumer;
    private final KafkaProducer<String, KafkaItemMessage> producer;
    private final ItemStatusProducer                      statusProducer;

    // ---- Task execution ----------------------------------------------------

    /**
     * Functional interface that wraps a single task execution.
     * The implementation calls {@code task.process(item)} and returns.
     * Tasks are instantiated outside this class (e.g. in {@link TaskAgentLauncher}).
     */
    @FunctionalInterface
    public interface TaskProcessor {
        void process(IItem item) throws Exception;
    }

    private final TaskProcessor    taskProcessor;
    private final int              parallelism;
    private final ThreadPoolExecutor executor;
    private final Semaphore          slots;   // bounds in-flight items

    // ---- State -------------------------------------------------------------

    private final AtomicInteger  inFlight  = new AtomicInteger(0);
    private volatile boolean     running   = true;
    private final CoordinatorClient coordinator;
    private final DistributedConfig cfg;

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    public TaskAgent(String caseId,
                     String taskType,
                     int stageNumber,
                     TaskProcessor taskProcessor,
                     DistributedConfig cfg,
                     CoordinatorClient coordinator) {
        this.agentId       = UUID.randomUUID().toString();
        this.caseId        = caseId;
        this.taskType      = taskType;
        this.stageNumber   = stageNumber;
        this.inputTopic    = TopicProvisioner.stageTopic(caseId, stageNumber);
        this.outputTopic   = TopicProvisioner.stageTopic(caseId, stageNumber + 1);
        this.rawTopic      = TopicProvisioner.stageTopic(caseId, 0);
        this.taskProcessor = taskProcessor;
        this.parallelism   = cfg.getAgentParallelism();
        this.cfg           = cfg;
        this.coordinator   = coordinator;

        this.slots    = new Semaphore(parallelism);
        this.executor = new ThreadPoolExecutor(
                parallelism, parallelism,
                60L, TimeUnit.SECONDS,
                new LinkedBlockingQueue<>(parallelism * 2),
                r -> { Thread t = new Thread(r, taskType + "-worker-" + agentId.substring(0,8)); return t; },
                new ThreadPoolExecutor.CallerRunsPolicy()
        );

        this.consumer      = buildConsumer(cfg);
        this.producer      = buildProducer(cfg);
        this.statusProducer = new ItemStatusProducer(cfg.getKafkaBootstrapServers());

        LOGGER.info("TaskAgent created: taskType={}, stage={}, input={}, output={}, parallelism={}",
                taskType, stageNumber, inputTopic, outputTopic, parallelism);
    }

    // -----------------------------------------------------------------------
    // Lifecycle
    // -----------------------------------------------------------------------

    /** Starts the agent — blocks until {@link #stop()} is called. */
    public void start() {
        coordinator.register(AgentRegistration.of(
                agentId, taskType, stageNumber, parallelism,
                java.net.InetAddress.getLoopbackAddress().getHostName()));

        consumer.subscribe(Collections.singletonList(inputTopic));
        LOGGER.info("TaskAgent '{}' (type={}) subscribed to '{}'", agentId, taskType, inputTopic);

        Thread heartbeatThread = new Thread(this::heartbeatLoop, taskType + "-heartbeat");
        heartbeatThread.setDaemon(true);
        heartbeatThread.start();

        try {
            while (running) {
                ConsumerRecords<String, KafkaItemMessage> records =
                        consumer.poll(Duration.ofMillis(500));

                for (ConsumerRecord<String, KafkaItemMessage> record : records) {
                    if (!running) break;
                    // Acquire a processing slot (backpressure)
                    try {
                        slots.acquire();
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        break;
                    }
                    inFlight.incrementAndGet();
                    final KafkaItemMessage msg = record.value();
                    executor.submit(() -> processRecord(msg));
                }
            }
        } finally {
            LOGGER.info("TaskAgent '{}' consumer loop exiting", agentId);
            executor.shutdown();
            try { executor.awaitTermination(60, TimeUnit.SECONDS); } catch (InterruptedException ignored) {}
            consumer.close();
            producer.close();
            statusProducer.close();
            coordinator.unregister(agentId);
        }
    }

    public void stop() {
        running = false;
    }

    // -----------------------------------------------------------------------
    // Item processing
    // -----------------------------------------------------------------------

    private void processRecord(KafkaItemMessage msg) {
        long startMs = System.currentTimeMillis();
        try {
            LOGGER.debug("Processing item '{}' ({})", msg.getItemUuid(), msg.getPath());
            statusProducer.publishStarted(msg, taskType);

            // Deserialise to IItem
            IItem item = ItemConverter.toItem(msg);
            item.setTempAttribute(ItemConverter.ATTR_KAFKA_MSG, msg);

            // Override DatasourceRegistry for THIS thread so that any sub-items
            // generated by the task go back to stage.0 (full pipeline re-entry).
            IDatasourceRegistry prevRegistry = DatasourceRegistry.get();
            DatasourceRegistry.set(buildSubitemRegistry(msg));
            try {
                // *** Task code runs here — completely unchanged ***
                taskProcessor.process(item);
            } finally {
                DatasourceRegistry.set(prevRegistry);
            }

            // Forward updated item to next stage
            KafkaItemMessage updated = ItemConverter.mergeState(msg, item);
            producer.send(new ProducerRecord<>(outputTopic, updated.getItemUuid(), updated),
                    (meta, ex) -> {
                        if (ex != null) {
                            LOGGER.error("Failed to forward item '{}' to '{}'",
                                    msg.getItemUuid(), outputTopic, ex);
                        }
                    });

            long durationMs = System.currentTimeMillis() - startMs;
            statusProducer.publishCompleted(msg, taskType, durationMs);
            LOGGER.debug("Completed item '{}' in {}ms", msg.getItemUuid(), durationMs);

        } catch (Exception e) {
            long durationMs = System.currentTimeMillis() - startMs;
            LOGGER.error("Error processing item '{}' in task '{}': {}",
                    msg.getItemUuid(), taskType, e.getMessage(), e);
            statusProducer.publishError(msg, taskType, durationMs, e);
            sendToDeadLetterQueue(msg, e);
        } finally {
            inFlight.decrementAndGet();
            slots.release();
        }
    }

    /**
     * Returns a {@link IDatasourceRegistry} that redirects sub-item creation
     * back to stage-0 (raw topic) so sub-items flow through the full pipeline.
     */
    private IDatasourceRegistry buildSubitemRegistry(KafkaItemMessage parentMsg) {
        IDatasourceRegistry base = DatasourceRegistry.get();
        return new IDatasourceRegistry() {
            @Override
            public IItem createItem() { return base.createItem(); }

            @Override
            public void addItem(IItem subItem) {
                KafkaItemMessage subMsg = ItemConverter.toMessage(subItem, caseId);
                subMsg.setParentItemUuid(parentMsg.getItemUuid());
                producer.send(new ProducerRecord<>(rawTopic, subMsg.getItemUuid(), subMsg));
                statusProducer.publishSubitemDiscovered(subMsg);
            }

            @Override
            public void addItemFirst(IItem subItem) { addItem(subItem); }

            @Override
            public void prepareForQueue(IItem item, ICaseData caseData) {
                base.prepareForQueue(item, caseData);
            }

            @Override
            public String getTrackID(IItem item) { return base.getTrackID(item); }

            @Override
            public void onProgress(String p, Object o, Object n) { base.onProgress(p, o, n); }

            @Override
            public void setEnvVar(String k, String v) { base.setEnvVar(k, v); }
        };
    }

    private void sendToDeadLetterQueue(KafkaItemMessage msg, Exception cause) {
        String dlqTopic = inputTopic + cfg.getDeadLetterTopicSuffix();
        try {
            producer.send(new ProducerRecord<>(dlqTopic, msg.getItemUuid(), msg));
            LOGGER.info("Item '{}' sent to DLQ '{}'", msg.getItemUuid(), dlqTopic);
        } catch (Exception ex) {
            LOGGER.error("Could not send item '{}' to DLQ '{}'", msg.getItemUuid(), dlqTopic, ex);
        }
    }

    // -----------------------------------------------------------------------
    // Heartbeat
    // -----------------------------------------------------------------------

    private void heartbeatLoop() {
        while (running) {
            try {
                coordinator.heartbeat(agentId, parallelism - inFlight.get(), inFlight.get());
                Thread.sleep(cfg.getHeartbeatIntervalSeconds() * 1000L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                break;
            } catch (Exception e) {
                LOGGER.warn("Heartbeat failed: {}", e.getMessage());
            }
        }
    }

    // -----------------------------------------------------------------------
    // Kafka builders
    // -----------------------------------------------------------------------

    private KafkaConsumer<String, KafkaItemMessage> buildConsumer(DistributedConfig cfg) {
        Properties props = new Properties();
        props.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, cfg.getKafkaBootstrapServers());
        // Consumer group = caseId.taskType ensures one-agent-per-item per task type
        props.put(ConsumerConfig.GROUP_ID_CONFIG, caseId + "." + taskType);
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG,
                  KafkaItemDeserializer.class.getName());
        props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, true);
        props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, parallelism * 2);
        props.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG,
                  (int) (cfg.getItemTimeoutSeconds() * 1000L));
        return new KafkaConsumer<>(props);
    }

    private KafkaProducer<String, KafkaItemMessage> buildProducer(DistributedConfig cfg) {
        Properties props = new Properties();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, cfg.getKafkaBootstrapServers());
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
                  KafkaItemSerializer.class.getName());
        props.put(ProducerConfig.ACKS_CONFIG, "all");
        props.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, true);
        props.put(ProducerConfig.COMPRESSION_TYPE_CONFIG, "lz4");
        props.put(ProducerConfig.LINGER_MS_CONFIG, 5);
        return new KafkaProducer<>(props);
    }

    @Override
    public void close() {
        stop();
    }

    // ---- Accessors ---------------------------------------------------------
    public String getAgentId()   { return agentId; }
    public String getTaskType()  { return taskType; }
    public int    getInFlight()  { return inFlight.get(); }
    public int    getFreeSlots() { return slots.availablePermits(); }
}
