# blind profile — only deviations from built-in defaults

categories = [
    "Emails",
    "Text Documents",
    "PDF Documents",
    "HTML Documents",
    "RTF Documents",
    "Other Documents",
    "XML Files",
    "Databases",
    "Spreadsheets",
    "Presentations",
    "Contacts",
    "Chats",
    "Instant Messages",
    "Internet History",
    "Web Bookmarks",
    "Link files",
    "URL links",
    "Peer-to-peer",
    "Temporary Internet Texts",
    "Texts in System Folders",
    "Other Texts",
    "Scanned Documents",
    "Temporary Internet Images",
    "Other Images",
    "Georeferenced Files",
    "User Activities",
    "GDrive Synced Files",
    "Windows Registry",
]
