<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>iped</groupId>
        <artifactId>iped-parsers</artifactId>
        <version>4.4.0-SNAPSHOT</version>
    </parent>
    <artifactId>iped-parsers-main</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parsers-impl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-apk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-vcard</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-plist-detector</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-mp4-detector</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-video</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-tor</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-sqlite-detector</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-browsers</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-discord-cache</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-db-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-sqlite-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-database-edb</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-vlc</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-ares</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-emule</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-shareaza</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-skype</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-lnk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-usnjrnl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-eventtranscript</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-bittorrent</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-winx</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-gdrive</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-external</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-registry</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>iped</groupId>
            <artifactId>iped-parser-mail</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
