<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>iped</groupId>
        <artifactId>iped-parent</artifactId>
        <version>4.4.0-SNAPSHOT</version>
    </parent>

    <artifactId>iped-parsers</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>java-dbf</module>
        <module>iped-parsers-common</module>
        <module>iped-parser-apk</module>
        <module>iped-parser-vcard</module>
        <module>iped-parser-plist-detector</module>
        <module>iped-parser-mp4-detector</module>
        <module>iped-parser-video</module>
        <module>iped-parser-tor</module>
        <module>iped-parser-sqlite-detector</module>
        <module>iped-parser-browsers</module>
        <module>iped-parser-discord-cache</module>
        <module>iped-parser-db-base</module>
        <module>iped-parser-sqlite-core</module>
        <module>iped-parser-database-edb</module>
        <module>iped-parser-vlc</module>
        <module>iped-parser-ares</module>
        <module>iped-parser-emule</module>
        <module>iped-parser-shareaza</module>
        <module>iped-parser-skype</module>
        <module>iped-parser-lnk</module>
        <module>iped-parser-usnjrnl</module>
        <module>iped-parser-eventtranscript</module>
        <module>iped-parser-bittorrent</module>
        <module>iped-parser-winx</module>
        <module>iped-parser-security</module>
        <module>iped-parser-gdrive</module>
        <module>iped-parser-external</module>
        <module>iped-parser-registry</module>
        <module>iped-parser-mail</module>
        <module>iped-parsers-main</module>
        <module>iped-parsers-impl</module>
    </modules>

    <build>
    	<plugins>
    		<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
    	</plugins>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <configuration>
                    <configLocation>config/sun_checks.xml</configLocation>
                </configuration>
                <version>3.3.1</version>
            </plugin>
        </plugins>
    </reporting>
</project>
