package iped.distributed.status;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import iped.distributed.kafka.KafkaItemMessage;

import java.time.Instant;
import java.util.Map;

/**
 * A single status event published to the global {@code iped.status} Kafka topic.
 *
 * <p>All events for all cases and all task types flow through this single topic,
 * allowing a central monitor / dashboard to build a real-time view of the entire
 * distributed processing cluster.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ItemStatusEvent {

    public enum Type {
        /** A new item was discovered by a datasource reader. */
        DISCOVERED,
        /** A task agent started processing an item. */
        STARTED,
        /** A task agent finished processing an item successfully. */
        COMPLETED,
        /** A task agent decided not to process an item (not applicable). */
        SKIPPED,
        /** A task agent encountered an unrecoverable error. */
        ERROR,
        /** No COMPLETED received within the configured timeout window. */
        TIMEOUT,
        /** A sub-item was generated by a task and re-injected into the pipeline. */
        SUBITEM_DISCOVERED,
        /** The entire case reached the final pipeline stage. */
        CASE_COMPLETED
    }

    private Type    type;
    private String  caseId;
    private String  itemUuid;
    private String  itemPath;
    private String  taskType;       // null for DISCOVERED / CASE_COMPLETED
    private int     pipelineStage;
    private Instant timestamp;
    private long    durationMs;     // for COMPLETED / ERROR
    private String  errorMessage;   // for ERROR / TIMEOUT
    private String  errorClass;     // for ERROR
    private Map<String, Object> details;

    // ---- Factory methods ---------------------------------------------------

    public static ItemStatusEvent discovered(KafkaItemMessage msg) {
        ItemStatusEvent e = base(msg);
        e.type = Type.DISCOVERED;
        return e;
    }

    public static ItemStatusEvent started(KafkaItemMessage msg, String taskType) {
        ItemStatusEvent e = base(msg);
        e.type = Type.STARTED;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        return e;
    }

    public static ItemStatusEvent completed(KafkaItemMessage msg, String taskType, long durationMs) {
        ItemStatusEvent e = base(msg);
        e.type = Type.COMPLETED;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        e.durationMs = durationMs;
        return e;
    }

    public static ItemStatusEvent error(KafkaItemMessage msg, String taskType,
                                        long durationMs, Throwable cause) {
        ItemStatusEvent e = base(msg);
        e.type = Type.ERROR;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        e.durationMs = durationMs;
        e.errorMessage = cause != null ? cause.getMessage() : "unknown";
        e.errorClass   = cause != null ? cause.getClass().getName() : null;
        return e;
    }

    public static ItemStatusEvent skipped(KafkaItemMessage msg, String taskType) {
        ItemStatusEvent e = base(msg);
        e.type = Type.SKIPPED;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        return e;
    }

    public static ItemStatusEvent subitemDiscovered(KafkaItemMessage msg) {
        ItemStatusEvent e = base(msg);
        e.type = Type.SUBITEM_DISCOVERED;
        return e;
    }

    public static ItemStatusEvent caseCompleted(String caseId) {
        ItemStatusEvent e = new ItemStatusEvent();
        e.type = Type.CASE_COMPLETED;
        e.caseId = caseId;
        e.timestamp = Instant.now();
        return e;
    }

    private static ItemStatusEvent base(KafkaItemMessage msg) {
        ItemStatusEvent e = new ItemStatusEvent();
        e.caseId    = msg.getCaseId();
        e.itemUuid  = msg.getItemUuid();
        e.itemPath  = msg.getPath();
        e.timestamp = Instant.now();
        return e;
    }

    // ---- Getters / Setters -------------------------------------------------

    public Type    getType()          { return type; }
    public void    setType(Type v)    { type = v; }

    public String  getCaseId()        { return caseId; }
    public void    setCaseId(String v){ caseId = v; }

    public String  getItemUuid()      { return itemUuid; }
    public void    setItemUuid(String v) { itemUuid = v; }

    public String  getItemPath()      { return itemPath; }
    public void    setItemPath(String v) { itemPath = v; }

    public String  getTaskType()      { return taskType; }
    public void    setTaskType(String v) { taskType = v; }

    public int     getPipelineStage() { return pipelineStage; }
    public void    setPipelineStage(int v) { pipelineStage = v; }

    public Instant getTimestamp()     { return timestamp; }
    public void    setTimestamp(Instant v) { timestamp = v; }

    public long    getDurationMs()    { return durationMs; }
    public void    setDurationMs(long v) { durationMs = v; }

    public String  getErrorMessage()  { return errorMessage; }
    public void    setErrorMessage(String v) { errorMessage = v; }

    public String  getErrorClass()    { return errorClass; }
    public void    setErrorClass(String v) { errorClass = v; }

    public Map<String, Object> getDetails()           { return details; }
    public void                setDetails(Map<String,Object> v) { details = v; }
}
