package iped.distributed.status;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import iped.distributed.kafka.KafkaItemMessage;

import java.time.Instant;
import java.util.Map;

/**
 * A single status event published to the global {@code iped.status} Kafka topic.
 *
 * <p>All events for all cases and all task types flow through this single topic,
 * allowing a central monitor / dashboard to build a real-time view of the entire
 * distributed processing cluster.
 *
 * <h2>Schema versioning</h2>
 * <p>Every event carries a {@link #schemaVersion} integer field.  The current
 * version is {@link #SCHEMA_VERSION}.  Consumers use this field to handle
 * schema evolution:
 * <ul>
 *   <li>{@code schemaVersion == 0} — legacy event produced before versioning was
 *       introduced; treat identically to v1 (all current fields were already present).</li>
 *   <li>{@code schemaVersion == SCHEMA_VERSION} — current; process normally.</li>
 *   <li>{@code schemaVersion >  SCHEMA_VERSION} — produced by a newer agent; unknown
 *       fields are silently ignored via {@code @JsonIgnoreProperties(ignoreUnknown=true)};
 *       the consumer should log a warning and continue.</li>
 * </ul>
 *
 * <h2>Evolution rules</h2>
 * <ol>
 *   <li><b>Adding a field</b> (non-breaking): add the field, bump only the minor
 *       documentation version; {@code SCHEMA_VERSION} stays the same.  Existing consumers
 *       ignore the new field via {@code @JsonIgnoreProperties}.</li>
 *   <li><b>Removing or renaming a field</b> (breaking): bump {@code SCHEMA_VERSION},
 *       update this class, publish a migration note.  Old consumers relying on the
 *       field must be updated before the new producer is deployed.</li>
 *   <li><b>Changing the semantics of a field</b>: treat as breaking (bump version).</li>
 * </ol>
 *
 * <p>See {@code specs/88-distributed-status-events-schema.md} for the full field
 * catalogue, JSON examples, and topic configuration guidance.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ItemStatusEvent {

    /**
     * Current schema version.  Increment on every breaking change to the event
     * structure (see class-level Javadoc for what constitutes a breaking change).
     */
    public static final int SCHEMA_VERSION = 1;

    public enum Type {
        /** A new item was discovered by a datasource reader. */
        DISCOVERED,
        /** A task agent started processing an item. */
        STARTED,
        /** A task agent finished processing an item successfully. */
        COMPLETED,
        /** A task agent decided not to process an item (not applicable). */
        SKIPPED,
        /** A task agent encountered an unrecoverable error. */
        ERROR,
        /** No COMPLETED received within the configured timeout window. */
        TIMEOUT,
        /** A sub-item was generated by a task and re-injected into the pipeline. */
        SUBITEM_DISCOVERED,
        /** The entire case reached the final pipeline stage. */
        CASE_COMPLETED
    }

    /**
     * Schema version of this event.  Defaults to {@code 0} on deserialization of
     * legacy events that pre-date versioning (Jackson leaves the primitive at its
     * default when the field is absent from the JSON).  All events produced by the
     * current codebase carry {@link #SCHEMA_VERSION}.
     */
    private int     schemaVersion;   // 0 = legacy/pre-versioned
    private Type    type;
    private String  caseId;
    private String  itemUuid;
    private String  itemPath;
    private String  taskType;       // null for DISCOVERED / CASE_COMPLETED
    private int     pipelineStage;
    private String  mediaType;      // MIME type of the item; null for CASE_COMPLETED / TIMEOUT
    private Long    lengthBytes;    // raw byte length; null when unknown
    private String  agentId;        // ID of the agent that published this event; null for coordinator-generated events
    private Instant timestamp;
    private long    durationMs;     // for COMPLETED / ERROR
    private String  errorMessage;   // for ERROR / TIMEOUT
    private String  errorClass;     // for ERROR
    private Map<String, Object> details;

    // ---- Factory methods ---------------------------------------------------

    public static ItemStatusEvent discovered(KafkaItemMessage msg) {
        ItemStatusEvent e = base(msg);
        e.type = Type.DISCOVERED;
        return e;
    }

    public static ItemStatusEvent started(KafkaItemMessage msg, String taskType) {
        ItemStatusEvent e = base(msg);
        e.type = Type.STARTED;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        return e;
    }

    public static ItemStatusEvent completed(KafkaItemMessage msg, String taskType, long durationMs) {
        ItemStatusEvent e = base(msg);
        e.type = Type.COMPLETED;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        e.durationMs = durationMs;
        return e;
    }

    public static ItemStatusEvent error(KafkaItemMessage msg, String taskType,
                                        long durationMs, Throwable cause) {
        ItemStatusEvent e = base(msg);
        e.type = Type.ERROR;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        e.durationMs = durationMs;
        e.errorMessage = cause != null ? cause.getMessage() : "unknown";
        e.errorClass   = cause != null ? cause.getClass().getName() : null;
        return e;
    }

    public static ItemStatusEvent skipped(KafkaItemMessage msg, String taskType) {
        ItemStatusEvent e = base(msg);
        e.type = Type.SKIPPED;
        e.taskType = taskType;
        e.pipelineStage = msg.getPipelineStage();
        return e;
    }

    public static ItemStatusEvent subitemDiscovered(KafkaItemMessage msg) {
        ItemStatusEvent e = base(msg);
        e.type = Type.SUBITEM_DISCOVERED;
        return e;
    }

    public static ItemStatusEvent timeout(String caseId, String itemUuid,
                                          String taskType, int pipelineStage,
                                          long sinceStartedMs) {
        ItemStatusEvent e = new ItemStatusEvent();
        e.schemaVersion = SCHEMA_VERSION;
        e.type = Type.TIMEOUT;
        e.caseId = caseId;
        e.itemUuid = itemUuid;
        e.taskType = taskType;
        e.pipelineStage = pipelineStage;
        e.durationMs = sinceStartedMs;
        e.errorMessage = "No completion within timeout window (" + sinceStartedMs + "ms since STARTED)";
        e.timestamp = Instant.now();
        return e;
    }

    public static ItemStatusEvent caseCompleted(String caseId) {
        ItemStatusEvent e = new ItemStatusEvent();
        e.schemaVersion = SCHEMA_VERSION;
        e.type = Type.CASE_COMPLETED;
        e.caseId = caseId;
        e.timestamp = Instant.now();
        return e;
    }

    private static ItemStatusEvent base(KafkaItemMessage msg) {
        ItemStatusEvent e = new ItemStatusEvent();
        e.schemaVersion = SCHEMA_VERSION;
        e.caseId      = msg.getCaseId();
        e.itemUuid    = msg.getItemUuid();
        e.itemPath    = msg.getPath();
        e.mediaType   = msg.getMediaType();
        e.lengthBytes = msg.getLength();
        e.timestamp   = Instant.now();
        return e;
    }

    // ---- Getters / Setters -------------------------------------------------

    public int     getSchemaVersion()        { return schemaVersion; }
    public void    setSchemaVersion(int v)   { schemaVersion = v; }

    public Type    getType()          { return type; }
    public void    setType(Type v)    { type = v; }

    public String  getCaseId()        { return caseId; }
    public void    setCaseId(String v){ caseId = v; }

    public String  getItemUuid()      { return itemUuid; }
    public void    setItemUuid(String v) { itemUuid = v; }

    public String  getItemPath()      { return itemPath; }
    public void    setItemPath(String v) { itemPath = v; }

    public String  getTaskType()      { return taskType; }
    public void    setTaskType(String v) { taskType = v; }

    public int     getPipelineStage() { return pipelineStage; }
    public void    setPipelineStage(int v) { pipelineStage = v; }

    public Instant getTimestamp()     { return timestamp; }
    public void    setTimestamp(Instant v) { timestamp = v; }

    public long    getDurationMs()    { return durationMs; }
    public void    setDurationMs(long v) { durationMs = v; }

    public String  getErrorMessage()  { return errorMessage; }
    public void    setErrorMessage(String v) { errorMessage = v; }

    public String  getErrorClass()    { return errorClass; }
    public void    setErrorClass(String v) { errorClass = v; }

    public String  getMediaType()               { return mediaType; }
    public void    setMediaType(String v)       { mediaType = v; }

    public Long    getLengthBytes()             { return lengthBytes; }
    public void    setLengthBytes(Long v)       { lengthBytes = v; }

    public String  getAgentId()                 { return agentId; }
    public void    setAgentId(String v)         { agentId = v; }

    public Map<String, Object> getDetails()           { return details; }
    public void                setDetails(Map<String,Object> v) { details = v; }
}
